### ISSUE TITLE
How to enable "logdebug" to be written to syslog

### ISSUE THREAD

**Issue by fcardona** [nodemailer/haraka-plugin-wildduck#1]
Hello. I am trying to figure out why wildduck is rejecting email. I believe it's related to the haraka-plugin-wildduck and would like to enable debug messages, [such as this one](https://github.com/nodemailer/haraka-plugin-wildduck/blob/174b29552188295c7eebb422af7837b20a6e61e6/index.js#L146), to be logged to file.

Here are some relevant logs which make me suspect that the plugin is not finding the recipient email in case you are interested...

```
May 18 20:36:48 email-server haraka[1626]: [NOTICE] [7A38DBAF-7414-4151-B8EA-1393939186AD.1] [core] sender <[sender_email]@gmail.com> code=CONT msg=""
May 18 20:36:48 email-server haraka[1626]: [INFO] [7A38DBAF-7414-4151-B8EA-1393939186AD.1] [core]  hook=rcpt plugin=wildduck function=hook_rcpt params=<[recipient_email]> retval=DENYSOFT msg="[object Object]"
May 18 20:36:48 email-server haraka[1626]: [NOTICE] [7A38DBAF-7414-4151-B8EA-1393939186AD.1] [core] recipient <[recipient_email]> code=DENYSOFT msg="[object Object]" sender=[sender_email]@gmail.com
May 18 20:36:48 email-server haraka[1626]: [NOTICE] [7A38DBAF-7414-4151-B8EA-1393939186AD.1] [core] disconnect ip=209.85.218.50 rdns=mail-oi0-f50.google.com helo=mail-oi0-f50.google.com relay=N early=N esmtp=Y tls=Y pipe=Y errors=0 txns=1 rcpts=0/1/0 msgs=0/0/0 bytes=0 lr="554
No valid recipients" time=0.419
```

**Comment by msimerson** [comment]
Use the syslog plugin: [https://www.npmjs.com/package/haraka-plugin-syslog](https://www.npmjs.com/package/haraka-plugin-syslog)
