### ISSUE TITLE
Problem with new versions

### ISSUE THREAD

**Issue by manalejandro** [nodemailer/haraka-plugin-wildduck#10]
I am using v1.28.1 of this plugin because latest versions seems broken with wildduck@latest

**Comment by louis-lau** [comment]
Hi! Please describe your issue, instead of `seems broken`. 😁

**Comment by manalejandro** [comment]
It crashes `haraka` since v1.28.1

```
haraka    | [CRIT] [-] [server] Plugin wildduck timed out on hook init_master - make sure it calls the callback
haraka    | [INFO] [-] [server]  hook=init_master plugin=wildduck function=init_wildduck_shared params="" retval=DENYSOFT msg="plugin timeout"
haraka    | [ERROR] [-] [server] init_master returned error: plugin timeout                    
haraka    | [NOTICE] [-] [core] Shutting down
```

**Comment by louis-lau** [comment]
As far as I can see between v1.28.1 and v1.28.2 there were only some minor dependency updates, nothing else. Is this a new installation? Or an upgraded installation?

**Comment by manalejandro** [comment]
Docker fresh containers using `node:10-slim` official image 🐋

**Comment by louis-lau** [comment]
Alright! 👍

The only thing I could think of was that maybe you didn't npm install on upgrade or something. But that clearly isn't a problem :)

Without testing myself I don't have any other ideas right now. Maybe Andris has some ideas.

**Comment by tfrancois** [comment]
So its 3 years later and I am getting this error as well - I can see emails coming in but they are not getting written to the mailboxes.  They just disapper into oblivion.  If not for the logs, I would never even know that the email was hitting the server.  Anyone know what causes this error?

**Comment by manalejandro** [comment]
Hi, i'm using this version in the Dockerfile and works fine with latest haraka and wildduck tags

ARG plugin_version=1.37.0

**Comment by madhavgharmalkar** [comment]
@tfrancois having the same issue. I switched to using LTMP and I'm having no issues yet. I just need to find a new way to check the destination with a RCTP hook

**Comment by msimerson** [comment]
This plugin just opens the DB connections (to redis & mongo) on init_master. If the plugin is timing out, it's likely because you need to edit the redis.host and/or mongo.url setting in wildduck.toml.
