### ISSUE TITLE
Mails are not queued

### ISSUE THREAD

**Issue by Haringat** [nodemailer/haraka-plugin-wildduck#11]
I have configured redis and mongodb on this plugin's config, wildduck and zone-mta equally. However, when I connect to haraka using thunderbird and send a message, I can see in the log the final line is 'queue code=OK msg="Message processed (D74D82B2-A9AB-401A-87AB-6293CF250DDA.1)"', however, it never arrives in the mongodb (and thus never at the recipient). When I try it using wildduck's web interface it works flawlessly though.

Also (I am not sure if it is related) incoming mails are also not forwarded to wildduck for storage.

Versions:
Haraka: 2.8.25
wildduck: 1.30.3
haraka-plugin-wildduck: 1.29.7
zone-mta: 1.7.0

**Comment by louis-lau** [comment]
Haraka is for incoming email transmission only. Zonemta should be used directly for outbound submission, and transmission.

**Comment by Haringat** [comment]
@louis-lau Thank you. Now that part works flawlessly. However, incoming mails are still not forwarded to wildduck. Should I open another issue for that or should we discuss that further here?

**Comment by louis-lau** [comment]
No, here would be fine. I haven't looked at the code, but I assume that `OK` is only returned by haraka-plugin-wildduck after storing the plugin successfully. Are you sure they aren't going to another database?

**Comment by andris9** [comment]
For every stored message you should see similar line in the Haraka logs:

```
[INFO] [F7C34E34-1645-43BF-8D13-CB1B97708F2F.1] [wildduck] STORED rcpt=andris@example.com user=andris@example.com[5cff6b395b445008c58024e5] result=Message stored as 5fb54c5d0e0f5d666c4b5b2c
```

if there is no such line then Haraka has not loaded WIldDuck plugin and is storing emails to /dev/null. See the logs immediately after Haraka startup to see any plugin initialisation errors.

If the line is there though, then Haraka is storing these messages *somehwere*, You have to figure out where.

**Comment by Haringat** [comment]
@andris9 I found the culprit. I still had the rcpt_to.access plugin loaded (before wildduck) and that conflicted. Commented that out and now it works. Sorry for the confusion and thank you for the help.
