### ISSUE TITLE
How to add additional address to all emails

### ISSUE THREAD

**Issue by kesavkolla** [nodemailer/haraka-plugin-wildduck#9]
For security compliance I want to route all incoming emails to a specified address. Is it possible to add an additional recipient to all incoming emails in haraka?

**Comment by andris9** [comment]
Currently you can use wildcards either as user part or domain part but not both, so there is no catch-all option. If you would add an address like `*@example.com`->`user@example.com` then emails to `test123@example.com` would be delivered to `user@example.com` but emails to `test123@test.com` would be rejected as there is no suitable match. Wildcard for domain is mainly meant for addresses like `postmaster@*`, `abuse@*` etc.

**Comment by SpoortiPalakshaiah** [comment]
I have created user as` all@example.com` and added address using `curl -i -XPOST https://<domain>/users/:user/addresses -H 'Content-type: application/json' -d '{ "address": "*@example.com","allowWildcard":true}'`. But the mail sent to `some_recipient@example.com` is not delivered to `all@example.com`

**Comment by andris9** [comment]
Is some_recipient@example.com a registered address?

What happens with the email? Does it get rejected?

**Comment by SpoortiPalakshaiah** [comment]
@andris9 
` some_recipient@example.com` is the registered address and the mail is getting delievered to ` some_recipient@example.com`

**Comment by andris9** [comment]
I see. Wildcard addresses are catchall addresses, not copies - email is routed either to a registered address or to a catchall address but not both. You would have to write a custom plugin for haraka that adds additional address to the recipients list during the rcpt_to hook and load the plugin before WildDuck plugin. This way WildDuck would see that the message is not for one but two accounts.
